Feature/administration attentats
SocialGouv/medle pull request #150
Opened 2021-05-31 14:50 UTC by kevingrilloaccenture

2021-05-31 15:06 UTC, pom421 commented
Salut @kevingrilloaccenture, 

Pour répondre à ta question, voici l'export de la table attacks : 

```
[
  {
    "id": 1,
    "created_at": "2020-01-20 19:55:53.300334",
    "updated_at": "2020-05-28 12:46:09.175123",
    "deleted_at": null,
    "name": "2015 Bataclan"
  },
  {
    "id": 5,
    "created_at": "2020-05-14 15:39:09.084248",
    "updated_at": "2020-05-28 12:46:09.175123",
    "deleted_at": null,
    "name": "2020 Villejuif"
  },
  {
    "id": 6,
    "created_at": "2020-05-14 15:39:09.084248",
    "updated_at": "2020-05-28 12:46:09.175123",
    "deleted_at": null,
    "name": "2012 École Ozar Hatorah Toulouse"
  },
  {
    "id": 2,
    "created_at": "2020-01-20 19:55:53.300334",
    "updated_at": "2020-05-28 12:46:09.175123",
    "deleted_at": null,
    "name": "2015 Hyper Cacher"
  },
  {
    "id": 3,
    "created_at": "2020-05-14 15:39:09.084248",
    "updated_at": "2020-05-28 12:46:09.175123",
    "deleted_at": null,
    "name": "2015 Les terrasses Paris"
  },
  {
    "id": 7,
    "created_at": "2020-05-14 15:39:09.084248",
    "updated_at": "2020-05-28 12:46:09.175123",
    "deleted_at": null,
    "name": "2015 Charlie Hebdo"
  },
  {
    "id": 4,
    "created_at": "2020-05-14 15:39:09.084248",
    "updated_at": "2020-05-28 12:46:09.175123",
    "deleted_at": null,
    "name": "2016 Nice"
  },
  {
    "id": 8,
    "created_at": "2020-11-05 14:47:03.243121",
    "updated_at": "2020-11-05 14:48:08.873098",
    "deleted_at": null,
    "name": "2020 Notre-Dame Nice"
  }
]
```

2021-06-03 14:45 UTC, kevingrilloaccenture commented
Bonjour @pom421,
merci pour ce retour.

Nous avons créé un script Knex générique permettant de récupérer la date et l'ajouter au champ "year".

2021-06-07 08:05 UTC, pom421 requested changes

2021-06-10 09:50 UTC, pom421 commented
OK pour les modifications 👍 .

J'ai modifié quelques petites choses : 
-  checkValidUserWithPrivilege(ACT_CONSULTATION, req, res) pour l'api /attacks/[id] en GET, à l'identique de l'api qui renvoie la liste
- ajout d'un order knex dans services/attacks/search, pour avoir les lignes les plus récentes en haut

D'autre part, j'ai utilisé ma configuration pour lancer prettier sur les fichiers que j'ai regardés. En particulier, il y avait des simples quotes et des points virgules, alors que c'est configuré pour les double quotes et pas de point virgules. 

Si tu utilises vscode, le .settings.json est censé te reformater ton ficher à chaque enregistrement et ne jamais plus avoir à se poser de question dessus ;). Je te conseille un truc du même genre sur ton ide, soit en automatique, soit en manuel.

Un yarn lint --fix doit corriger la plupart des warning qu'il y a à l'heure actuelle. Je vous laisse le faire si vous le voulez. (à faire dans une PR à part).

2021-06-10 09:51 UTC, pom421 approved these changes

2021-06-10 12:28 UTC, pom421 commented
J'ai aussi modifié les seeds 04/attacks.js qui n'étaient pas dans la forme attendue avec la date.

2021-06-10 12:40 UTC, merged